issuer: http://localhost:5556/dex
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
web:
  http: 0.0.0.0:5556
staticClients:
- id: grafana
  redirectURIs:
  - http://localhost:3000/login/generic_oauth
  name: Grafana
  secret: supersecret
enablePasswordDB: true
staticPasswords:
- email: admin@example.com
  # bcrypt hash for the literal password "password"
  hash: $2a$10$7EqJtq98hPqEX7fNZaFWoO0rISFiC9eje1na43EIBgzHuLlHotxCq
  username: admin
  userID: 08a8684b-388c-49b0-83da-8c41f70e4fb3
