apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aegis
  template:
    metadata:
      labels:
        app: aegis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      volumes:
        - name: certs
          secret:
            secretName: aegis-tls
      containers:
        - name: api
          image: clyrai/aegis:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: AEGIS_REQUIRE_MTLS_SIM
              value: "1"
            - name: GUNICORN_WORKERS
              value: "2"
            - name: GUNICORN_BIND
              value: "0.0.0.0:8000"
            - name: GUNICORN_TIMEOUT
              value: "60"
          volumeMounts:
            - name: certs
              mountPath: /etc/aegis/certs
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
