{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aegis.fullname" . }}
  {{- with .Values.serviceMonitor.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "aegis.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    {{- if .Values.serviceMonitor.namespace }}
    matchNames:
      - {{ .Values.serviceMonitor.namespace }}
    {{- else }}
    any: true
    {{- end }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}
