apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aegis
  template:
    metadata:
      labels:
        app: aegis
    spec:
      containers:
        - name: api
          image: clyrai/aegis:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: aegis
spec:
  selector:
    app: aegis
  ports:
    - name: http
      port: 80
      targetPort: 8000
