name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check .
      - name: Type-check (mypy)
        run: |
          pip install mypy types-requests types-PyYAML
          mypy --ignore-missing-imports aegis
      - name: Tests
        run: pytest -q
      - name: Docs build (mkdocs --strict)
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build --strict
      - name: Build container
        run: |
          docker build -t aegis:test .
      - name: Generate SBOM (repo)
        uses: anchore/sbom-action@v0.17.6
        with:
          path: .
          artifact-name: sbom-repo-spdx.json
          format: spdx-json
      - name: Generate SBOM (image)
        uses: anchore/sbom-action@v0.17.6
        with:
          image: aegis:test
          artifact-name: sbom-image-spdx.json
          format: spdx-json
      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-fs.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
      - name: Trivy Config (IaC) scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-config.sarif'
          exit-code: '0'
      - name: Trivy Image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'aegis:test'
          format: 'sarif'
          output: 'trivy-image.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
      - name: Upload Trivy SARIF (FS)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
      - name: Upload Trivy SARIF (Config)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-config.sarif
      - name: Upload Trivy SARIF (Image)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2
      - name: Helm lint
        run: |
          helm lint deploy/helm/aegis || true
      - name: Upload benchmark artifacts
        if: always()
        run: |
          python benchmarks/benchmark_training_speed.py --output speed.csv || true
          python benchmarks/benchmark_dp_tradeoff.py --output tradeoff.csv || true
          python benchmarks/benchmark_report_runtime.py --output report_runtime.csv || true
          python benchmarks/generate_attack_metrics.py --output attack_metrics.csv || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: benchmark-artifacts
          path: |
            speed.csv
            tradeoff.csv
            report_runtime.csv
            attack_metrics.csv
            sbom-repo-spdx.json
            sbom-image-spdx.json
